theme = "adwaita-dark"

[editor]

auto-pairs=false
bufferline = "multiple"

[keys.select."\\"]

"s" = ":pipe-to tmux load-buffer - ; tmux paste-buffer -t $(tmux display-message -p '#{session_name}:#{window_index}').$(($(tmux display-message -p '#{pane_index}')+1))"

[keys.normal."\\"]

"s" = ":pipe-to tmux load-buffer - ; tmux paste-buffer -t $(tmux display-message -p '#{session_name}:#{window_index}').$(($(tmux display-message -p '#{pane_index}')+1))"

