theme = "base16_default"

[editor]

auto-pairs = false
bufferline = "multiple"

[editor.cursor-shape]

insert = "bar"
normal = "block"

[keys.normal]

x = ["goto_line_start", "select_mode", "goto_line_end_newline"]
X = ["goto_line_start", "select_mode", "goto_line_end_newline"]

[keys.normal."\\"]

"s" = ":pipe-to tmux load-buffer - ; tmux paste-buffer -t $(tmux display-message -p '#{session_name}:#{window_index}').$(($(tmux display-message -p '#{pane_index}')+1))"

[keys.insert]

esc = ["collapse_selection", "normal_mode", "move_char_left"]

[keys.select]

x = "extend_line_below"
X = "extend_line_above"

[keys.select."\\"]

"s" = ":pipe-to tmux load-buffer - ; tmux paste-buffer -t $(tmux display-message -p '#{session_name}:#{window_index}').$(($(tmux display-message -p '#{pane_index}')+1))"
