#!/bin/sh

xrandr --output DisplayPort-0 --auto --primary --output eDP --off

# Рабочие столы.
bspc monitor DisplayPort-0 -d 1 2 3 4 5

# Загрузка кастомной раскладки только с помощью setxkbmap почему-то не всегда
# работает, поэтому сначала генерируем раскладку, а потом загружаем с помощью
# xkbcomp.
# setxkbmap -I"$HOME/.config/xkb" -layout myus,myru -option "grp:caps_toggle" -option "lv3:menu_switch" -print | xkbcomp -I"$HOME/.config/xkb" - "$DISPLAY"

setxkbmap -layout us,ru -option "grp:caps_toggle" -option "compose:menu"

# Таймер отключения экрана в секундах.
xset -dpms
xset s off

# Добавляем шрифты из домашней папки.
xset +fp $HOME/.fonts
xset fp rehash

# Устанавливаем обои и курсор.
xsetroot -solid black
xsetroot -cursor_name left_ptr

# Чтобы приложения на java нормально отображались.
wmname LG3D

# Загружаем ресурсы.
xrdb -merge ~/.Xresources

# Приложение для отображения уведомлений.
dunst &
