#!/bin/sh

xrandr --output eDP1 --auto

# Рабочие столы.
bspc monitor eDP1 -d 1 2 3 4 5

# Раскладка.
setxkbmap -layout us,ru -option "grp:caps_toggle" -option "compose:menu"

# Таймер отключения экрана в секундах.
xset dpms 2000 2000 2000

# Добавляем шрифты из домашней папки.
xset +fp $HOME/.fonts
xset fp rehash

# Устанавливаем обои и курсор.
xsetroot -solid black
xsetroot -cursor_name left_ptr

# Чтобы приложения на java нормально отображались.
wmname LG3D

# Загружаем ресурсы.
xrdb -merge ~/.Xresources

polybar &
