[font]
size = 16

[font.normal]
family = "Ioskeley Mono"

[[keyboard.bindings]]
chars = "\u001B[9;5u"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[9;6u"
key = "Tab"
mods = "Control|Shift"

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "0x0e3c46"
foreground = "0xC7DBDD"

[colors.cursor]
text = "0x0e3c46"
cursor = "0xC7DBDD"

[colors.normal]
black = "0x0e3c46"
red = "0xfb6953"
green = "0x73d8ad"
yellow = "0xfce380"
blue = "0x46bddd"
magenta = "0x756b8a"
cyan = "0x3fb2b9"
white = "0xC7DBDD"

[colors.bright]
black = "0x587073"
red = "0xfb6953"
green = "0x73d8ad"
yellow = "0xfce380"
blue = "0x46bddd"
magenta = "0x756b8a"
cyan = "0x3fb2b9"
white = "0xD2FAFF"
