#!/bin/sh

hostname=$(hostname | cut -d '.' -f 1)

# Настраиваем горячие клавиши.
pgrep -x sxhkd > /dev/null \
    || env SXHKD_SHELL=/bin/sh sxhkd -c "$HOME/.config/sxhkd/sxhkdrc"           \
                "$HOME/.config/sxhkd/sxhkdrc.bspwm"     \
                "$HOME/.config/sxhkd/sxhkdrc#$hostname" &

bspc config border_width            2
bspc config window_gap              0

# Не изменять размеры окон для точного соответствия сетке (чтобы не было
# рамки в терминале).
# bspc config honor_size_hints        true

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config automatic_scheme        alternate

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

bspc config ignore_ewmh_focus       true

bspc rule -a firefox focus=off follow=off

exec "$HOME/.config/bspwm/bspwmrc#$hostname"
