#! /bin/sh

hostname=$(hostname | cut -d '.' -f 1)

# Настраиваем горячие клавиши.
pgrep -x sxhkd > /dev/null \
    || sxhkd -c "$HOME/.config/sxhkd/sxhkdrc"           \
                "$HOME/.config/sxhkd/sxhkdrc.bspwm"     \
                "$HOME/.config/sxhkd/sxhkdrc#$hostname" &

bspc config border_width             2
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

exec "$HOME/.config/bspwm/bspwmrc#$hostname"

