colorscheme reeder
set global tabstop 4
set global indentwidth 4

add-highlighter global/ number-lines -relative

evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}

plug "andreyorst/plug.kak" noload
plug "andreyorst/fzf.kak"
plug "h-youhei/kakoune-surround"

eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable
